#release configuration
#Thu Sep 17 23:13:48 IST 2026
scm.tagNameFormat=@{project.version}
exec.additionalArguments=-Prelease -P openmrs
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
pushChanges=true
completedPhase=create-backup-poms
scm.url=scm\:git\:git@github.com\:Gamshan/openmrs-digipath-connector.git
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
