#release configuration
#Thu Sep 17 23:09:45 IST 2026
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
project.rel.org.openmrs.module\:digipath.connector=1.0.1
project.scm.org.openmrs.module\:digipath.connector-omod.empty=true
completedPhase=end-release
scm.url=scm\:git\:git@github.com\:Gamshan/openmrs-digipath-connector.git
project.scm.org.openmrs.module\:digipath.connector.connection=scm\:git\:git@github.com\:Gamshan/openmrs-digipath-connector.git
project.scm.org.openmrs.module\:digipath.connector-api.empty=true
project.dev.org.openmrs.module\:digipath.connector=1.0.2-SNAPSHOT
project.scm.org.openmrs.module\:digipath.connector.tag=HEAD
exec.additionalArguments=-Prelease -P openmrs
scm.tagNameFormat=@{project.version}
pushChanges=true
project.dev.org.openmrs.module\:digipath.connector-api=1.0.2-SNAPSHOT
project.rel.org.openmrs.module\:digipath.connector-api=1.0.1
project.dev.org.openmrs.module\:digipath.connector-omod=1.0.2-SNAPSHOT
scm.tag=1.0.1
project.scm.org.openmrs.module\:digipath.connector.url=https\://github.com/Gamshan/openmrs-digipath.connector/
project.rel.org.openmrs.module\:digipath.connector-omod=1.0.1
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
project.scm.org.openmrs.module\:digipath.connector.developerConnection=scm\:git\:git@github.com\:Gamshan/openmrs-digipath-connector.git
